apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-nginx-chart.fullname" . }}-html
data:
  index.html: |
    <html>
      <head><title>Hello</title></head>
      <body>
        <h1>hello world</h1>
      </body>
    </html>

