{{- range .Values.autoSyncProjects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  destinations:
  - namespace: '{{ .namespace }}'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
{{- end }}
